process: "decoder_hifiD"
#train_path: 'G:\dataset\Oxford102\102flowers_GAN\train'
#val_path: 'G:\dataset\Oxford102\102flowers_GAN\test'
train_path: 'G:\dataset\imagenette2-320\original-dataset\train'
val_path: 'G:\dataset\imagenette2-320\original-dataset\test'
checkpoint_enhdec_path: 'weights/cls_RB_0.09bpp.pth'
checkpoint_path: ''
epochs: 100
learning_rate: 0.00005
milestones: [50]
gamma: 0.5
num_workers: 2
lambda_L2: 250
lambda_G: 20
lambda_LPIPS: 20
batch_size: 8
val_batch_size: 1
cuda: True
